name: license-check
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check license
        run: make license-check